spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

# 관리자 정보 - 환경변수로 주입
admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
  email: ${ADMIN_EMAIL}